name: "Quarkiverse UI Docs"
description: "Generate your asciidoc documentation with Quarkiverse look and feel"
inputs:
  github-token:
    description: "GitHub token"
    required: true
  action:
    description: "Name of the action (if named)"
    required: false

runs:
  using: "composite"
  steps:
    - name: Inject quarkus-github-action repository credentials
      shell: bash
      run: |
        if [ -f ~/.m2/settings.xml ]; then
          if ! grep -q '<id>quarkus-github-action</id>' ~/.m2/settings.xml; then
            sed -i.bak 's@</servers>@<server><id>quarkus-github-action</id><username>${env.GITHUB_ACTOR}</username><password>${env.GITHUB_TOKEN}</password></server></servers>@' ~/.m2/settings.xml
          fi
        else
          mkdir -p ~/.m2/
          cat <<\EOF > ~/.m2/settings.xml
        <?xml version="1.0"?>
        <settings>
          <servers>
            <server>
              <id>quarkus-github-action</id>
              <username>${env.GITHUB_ACTOR}</username>
              <password>${env.GITHUB_TOKEN}</password>
            </server>
          </servers>
        </settings>
        EOF
        fi
    - name: Set up JBang
      uses: jbangdev/setup-jbang@main
    - name: Run the action
      id: action
      run: jbang --java 17 --fresh --repos 'quarkus-github-action=https://maven.pkg.github.com/mcruzdev/quarkiverse-ui-docs/' --repos 'mavencentral' io.quarkiverse:quarkiverse-ui-docs:999-SNAPSHOT
      shell: bash
      env:
        JSON_INPUTS: ${{ toJSON(inputs) }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
